{
 "title": "Observability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Process alive since",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"backend\"}"
    }
   ]
  },
  {
   "title": "Log by Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(level) (rate({job=\"backend\"} [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"5.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{handler!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (http_requests_total{})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fastapi_exceptions_total{}" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_highr_seconds_sum{} / http_request_duration_highr_seconds_count{}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Process virtual memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes{}", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{app_name=\"$app_name\", status=~\"2.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{app_name=\"$app_name\", handler!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}