version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      PGDATABASE: keycloak
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: postgres
      PGPORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak-server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/keycloak-server.key.pem
    volumes:
      - ./keys:/opt/keycloak/conf
      - ./keycloak_data:/opt/keycloak/data/h2
    ports:
      - "8080:8080"
      - "8443:8443"
    command:
      - "start-dev"
  fastapi:
    image: python:3.12
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      CLIENT_ID: "cli-dottori"
      CLIENT_SECRET: dFVs0dyOq8okog72gsn5z7h8qCzp6PW9
      REALM_NAME: serenade
    volumes:
      - ./api:/api
    working_dir: /api
    command: >
      bash -c "python -m venv venv && source venv/bin/activate &&
               pip install --no-cache-dir -r requirements.txt --upgrade &&
               python main.py"
    ports:
      - "8000:8000"
