  version: '3.8'
  
  services:
    dbkeycloak:
      image: postgres:latest
      env_file:
        - .envars/.env.dbkeycloak
      ports:
        - ${DB_KEYCLOAK_PORT}:5432
    dbpercona:
      image: perconalab/postgres-tde-ext:latest
      env_file:
        - .envars/.env.dbpercona
      volumes:
        - ./dbpercona/init.sql:/docker-entrypoint-initdb.d/wewe.sql
      ports:
        - ${DB_PERCONA_PORT}:5432
    keycloak:
      image: quay.io/keycloak/keycloak:latest
      env_file:
        - .envars/.env.keycloak
      volumes:
        - ./.keys:/opt/keycloak/conf
        - ./.keycloak_data/keycloakdb.mv.db:/opt/keycloak/data/h2/keycloakdb.mv.db
      ports:
        - 8080:8080
        - 8443:8443
      command:
        - "start-dev"
    backend:
      image: python:3.12
      env_file:
        - .envars/.env.backend
      volumes:
        - ./backend/app:/app
      working_dir: /app
      command: >
        bash -c "pip install --no-cache-dir -r requirements.txt && python main.py"
      ports:
        - ${APP_BACKEND_PORT}:8000
