version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak-server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/keycloak-server.key.pem
      KC_HTTP_RELAITVE_PATH: /auth
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    volumes:
      - realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    ports:
      - "8080:8080"
      - "8443:8443"
    command:
      - "start-dev"
  fastapi:
    image: python:3.12
    volumes:
      - ./api:/api
    working_dir: /api
    command: >
      bash -c "python -m venv venv && source venv/bin/activate &&
               pip install --no-cache-dir -r requirements.txt --upgrade &&
               python main.py"
    ports:
      - "8000:8000"
