version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  percona:
    image: perconalab/postgres-tde-ext
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/wewe.sql
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      PGDATABASE: keycloak
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: postgres
      PGPORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak-server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/keycloak-server.key.pem
    volumes:
      - ./keys:/opt/keycloak/conf
      - ./keycloak_data:/opt/keycloak/data/h2
    ports:
      - "8080:8080"
      - "8443:8443"
    command:
      - "start-dev"
  fastapi:
    image: python:3.12
    environment:
      KEYCLOAK_URL: http://keycloak:8080/
      CLIENT_ID: "fastapi-be"
      CLIENT_SECRET: 32lfgwv1jLynVSoUpNveN5ieP5qVR9ZJ
      REALM_NAME: serenade
    volumes:
      - ./api:/api
    working_dir: /api
    command: >
      bash -c "python -m venv venv && source venv/bin/activate &&
               pip install --no-cache-dir -r requirements.txt --upgrade &&
               python main.py"
    ports:
      - "8000:8000"
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - keycloak
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana-data"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "Ut0mhMHSTnA5AKbYDUlgutourwox2q7J"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://keycloak:8080/auth/realms/serenade/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://keycloak:8080/auth/realms/serenade/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://keycloak:8080/auth/realms/serenade/protocol/openid-connect/userinfo"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[], 'imt') && 'Admin' || 'Viewer'"
      GF_SERVER_ROOT_URL: "http://localhost:4000/"
    ports:
      - "4000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: