# Ticket
TICKET_OPEN = "APERTO"
TICKET_CLOSED = "CHIUSO"

# Patient
INSTALLATION_OPENING = "IN INSTALLAZIONE"
INSTALLATION_OPEN = "FUNZIONANTE"
INSTALLATION_PAUSE = "IN MANUTENZIONE"
INSTALLATION_CLOSING = "IN DISINSTALLAZIONE"
INSTALLATION_CLOSED = "INATTIVO"
INSTALLATION_UNKNOW = "STATO SCONOSCIUTO"

# CATEGORY
TICKET_INSTALLATION = "installazione"
TICKET_MAINTENANCE = "manutenzione"
TICKET_UNINSTALLATION = "disinstallazione"
