defaultEntryPoints = [
  "http",
  "https",
  ]

[entryPoints]
  [entryPoints.web]
    address = ":80"
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    exposedbydefault=false
  [providers.file]
    directory = "/etc/traefik/dyn"

[docker]
  domain = "docker.local"
  watch = true

[api]
  insecure = true
  dashboard = true
  # debug = true

[log]
  level = "INFO"

[accessLog]
  [accessLog.fields.headers]
    defaultMode = "keep"
    [accessLog.fields.headers.names]
        RequestAddr = "keep"
        RequestHost = "keep"
        "User-Agent" = "drop"
